// One-off generator: looks up each title on the Google Books API and writes a
// dedupe-safe SQL seed file the user pastes into the Supabase SQL Editor.
// Run with: node scripts/seed-books.mjs
import { readFileSync, writeFileSync } from "node:fs";

// Pull the API key out of .env.local (this script runs outside Next.js).
const env = readFileSync(new URL("../.env.local", import.meta.url), "utf8");
const key = env.match(/^GOOGLE_BOOKS_API_KEY=(.+)$/m)?.[1]?.trim();
if (!key) throw new Error("GOOGLE_BOOKS_API_KEY not found in .env.local");

// Popular romantasy. We query by title + author and then pick the cleanest
// real single-novel edition from the candidates (Google's top hit is often a
// box set, sample, or wrong series entry). `want` is the canonical title the
// chosen result must match.
const TITLES = [
  { want: "A Court of Thorns and Roses", author: "Sarah J. Maas" },
  { want: "A Court of Mist and Fury", author: "Sarah J. Maas" },
  { want: "Throne of Glass", author: "Sarah J. Maas" },
  { want: "House of Earth and Blood", author: "Sarah J. Maas" },
  { want: "Fourth Wing", author: "Rebecca Yarros" },
  { want: "Iron Flame", author: "Rebecca Yarros" },
  { want: "From Blood and Ash", author: "Jennifer L. Armentrout" },
  { want: "A Kingdom of Flesh and Fire", author: "Jennifer L. Armentrout" },
  { want: "The Cruel Prince", author: "Holly Black" },
  { want: "Shadow and Bone", author: "Leigh Bardugo" },
  { want: "Six of Crows", author: "Leigh Bardugo" },
  { want: "Serpent & Dove", author: "Shelby Mahurin" },
  { want: "The Serpent and the Wings of Night", author: "Carissa Broadbent" },
  { want: "Powerless", author: "Lauren Roberts" },
  { want: "The Bridge Kingdom", author: "Danielle L. Jensen" },
];

const sqlString = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
// Editions we never want: box sets, samples, companions, etc.
const BAD = /(collection|box set|boxed|\bset\b|sample|excerpt|chapters?\s*\d|companion|coloring|guide|summary|analysis)/i;

async function lookup({ want, author }) {
  const url = new URL("https://www.googleapis.com/books/v1/volumes");
  url.searchParams.set("q", `intitle:"${want}" inauthor:"${author}"`);
  url.searchParams.set("maxResults", "8");
  url.searchParams.set("printType", "books");
  url.searchParams.set("langRestrict", "en");
  url.searchParams.set("country", "US");
  url.searchParams.set("key", key);

  const res = await fetch(url);
  if (!res.ok) throw new Error(`${want}: HTTP ${res.status}`);
  const data = await res.json();
  const items = data.items ?? [];

  const wantNorm = norm(want);
  const candidates = items
    .map((item) => ({ item, info: item.volumeInfo ?? {} }))
    .filter(({ info }) => {
      const title = info.title ?? "";
      if (BAD.test(title)) return false;
      // Title must match the canonical name (allowing a trailing subtitle).
      const t = norm(title);
      return t === wantNorm || t.startsWith(wantNorm + " ") || t.startsWith(wantNorm);
    });
  // Prefer a candidate that actually has a cover image.
  const chosen =
    candidates.find(({ info }) => info.imageLinks?.thumbnail) ?? candidates[0];
  if (!chosen) throw new Error(`${want}: no clean result among ${items.length}`);

  const { item, info } = chosen;
  const cover = (info.imageLinks?.thumbnail ?? null)?.replace(/^http:/, "https:");
  const year = info.publishedDate ? Number(info.publishedDate.slice(0, 4)) : null;
  // Drop a trailing edition/format subtitle, e.g. "Powerless: Deluxe ... Edition".
  let title = info.title ?? want;
  if (/edition|hardback|paperback|deluxe|collector/i.test(title) && title.includes(":")) {
    title = title.split(":")[0].trim();
  }
  return {
    googleBooksId: item.id,
    title,
    author: info.authors?.[0] ?? author,
    year: Number.isFinite(year) ? year : null,
    coverUrl: cover,
  };
}

const rows = [];
for (const entry of TITLES) {
  const b = await lookup(entry);
  console.log(`✓ ${b.title} — ${b.author} (${b.year})${b.coverUrl ? "" : "  [no cover]"}`);
  rows.push(b);
}

const values = rows
  .map(
    (b) =>
      `  (${sqlString(b.title)}, ${sqlString(b.author)}, ${
        b.year ?? "null"
      }, ${sqlString(b.coverUrl)}, ${sqlString(b.googleBooksId)})`,
  )
  .join(",\n");

const sql = `-- marginalia — seed the library with popular romantasy
-- Step 7. Run this in the Supabase SQL Editor (one paste). Safe to re-run:
-- the WHERE NOT EXISTS guard skips any book already in the library, matched
-- on its Google Books id, so you won't get duplicates.
--
-- Generated by scripts/seed-books.mjs from live Google Books data.

insert into public.books (title, author, year, cover_url, google_books_id)
select v.title, v.author, v.year, v.cover_url, v.google_books_id
from (values
${values}
) as v(title, author, year, cover_url, google_books_id)
where not exists (
  select 1 from public.books b where b.google_books_id = v.google_books_id
);
`;

writeFileSync(
  new URL("../supabase/migrations/0003_seed_romantasy_library.sql", import.meta.url),
  sql,
);
console.log(`\nWrote ${rows.length} books to 0003_seed_romantasy_library.sql`);
