-- marginalia — seed the library with popular romantasy
-- Step 7. Run this in the Supabase SQL Editor (one paste). Safe to re-run:
-- the WHERE NOT EXISTS guard skips any book already in the library, matched
-- on its Google Books id, so you won't get duplicates.
--
-- Generated by scripts/seed-books.mjs from live Google Books data.

insert into public.books (title, author, year, cover_url, google_books_id)
select v.title, v.author, v.year, v.cover_url, v.google_books_id
from (values
  ('A Court of Thorns and Roses', 'Sarah J. Maas', 2015, 'https://books.google.com/books/content?id=E-kdBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'E-kdBQAAQBAJ'),
  ('A Court of Mist and Fury', 'Sarah J. Maas', 2017, 'https://books.google.com/books/content?id=GcbMDgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'GcbMDgAAQBAJ'),
  ('Throne of Glass', 'Sarah J. Maas', 2013, 'https://books.google.com/books/content?id=r_i4_Lr5fA4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'r_i4_Lr5fA4C'),
  ('House of Earth and Blood', 'Sarah J. Maas', 2020, 'https://books.google.com/books/content?id=gswAEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'gswAEAAAQBAJ'),
  ('Fourth Wing', 'Rebecca Yarros', 2023, 'https://books.google.com/books/content?id=E-OLEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'E-OLEAAAQBAJ'),
  ('Iron Flame', 'Rebecca Yarros', 2023, 'https://books.google.com/books/content?id=xIS9EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'xIS9EAAAQBAJ'),
  ('From Blood and Ash', 'Jennifer L. Armentrout', 2020, 'https://books.google.com/books/content?id=SpXZDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'SpXZDwAAQBAJ'),
  ('A Kingdom of Flesh and Fire', 'Jennifer L. Armentrout', 2020, 'https://books.google.com/books/content?id=itXtDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'itXtDwAAQBAJ'),
  ('The Cruel Prince', 'Holly Black', 2018, 'https://books.google.com/books/content?id=h3YHuAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'h3YHuAEACAAJ'),
  ('Shadow and Bone', 'Leigh Bardugo', 2012, 'https://books.google.com/books/content?id=Mam8PZhfDCkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'Mam8PZhfDCkC'),
  ('Six of Crows', 'Leigh Bardugo', 2015, 'https://books.google.com/books/content?id=ZCtfCgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'ZCtfCgAAQBAJ'),
  ('Serpent & Dove', 'Shelby Mahurin', 2019, 'https://books.google.com/books/content?id=MPB8DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'MPB8DwAAQBAJ'),
  ('The Serpent and the Wings of Night', 'Carissa Broadbent', 2023, 'https://books.google.com/books/content?id=CQ0U0AEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'CQ0U0AEACAAJ'),
  ('Powerless', 'Lauren Roberts', 2024, 'https://books.google.com/books/content?id=o1PK0AEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'o1PK0AEACAAJ'),
  ('The Bridge Kingdom', 'Danielle L. Jensen', 2019, 'https://books.google.com/books/content?id=F8sJEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'F8sJEQAAQBAJ')
) as v(title, author, year, cover_url, google_books_id)
where not exists (
  select 1 from public.books b where b.google_books_id = v.google_books_id
);
